---
# role: bind
# file: molecule/multi/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "verify.yml"
  inventory:
    group_vars:
      all:
        bind_multi_tsig_secret: "9EovO6m9ap7fG3ndj0a47DOOPkU1Ui4TRGM/gE/IkC8="
        bind_zones: []
        bind_zone_files: []
        bind_tsig_keys:
          - name: "ddns"
            algorithm: "hmac-sha256"
            secret: "{{ bind_multi_tsig_secret }}"
        bind_listeners:
          - name: "listen-on"
            port: 53
            entries:
              - "127.0.0.1"
              - "{{ bind_multi_ip }}"
          - name: "listen-on-v6"
            port: 53
            entries:
              - "none"
        bind_options:
          - name: "recursion"
            value: "no"
          - name: "allow-query"
            entries:
              - "any"
          - name: "allow-recursion"
            entries:
              - "none"
          - name: "allow-transfer"
            entries:
              - "none"
          - name: "dnssec-validation"
            value: "no"
          - name: "minimal-responses"
            value: "yes"
          - name: "version"
            value: "none"
      bind_multi_primary:
        bind_zones:
          - name: "example.com"
            class: "IN"
            type: "primary"
            file: "{{ bind_multi_zone_file }}"
            update_policy:
              - action: "grant"
                identity: "ddns"
                match_type: "name"
                name: "update.example.com."
                types:
                  - "A"
            statements:
              - "allow-transfer { {{ bind_multi_secondary_ip }}; }"
              - "also-notify { {{ bind_multi_secondary_ip }}; }"
              - "notify yes"
        bind_zone_files:
          - name: "example.com"
            file: "{{ bind_multi_zone_file }}"
            primary: "ns1.example.com."
            email: "hostmaster.example.com."
            records:
              - name: "@"
                type: "NS"
                data: "ns1.example.com."
              - name: "@"
                type: "NS"
                data: "ns2.example.com."
              - name: "ns1"
                type: "A"
                data: "{{ bind_multi_primary_ip }}"
              - name: "ns2"
                type: "A"
                data: "{{ bind_multi_secondary_ip }}"
      bind_multi_secondary:
        bind_primaries:
          - name: "example-primary"
            entries:
              - "{{ bind_multi_primary_ip }}"
        bind_zones:
          - name: "example.com"
            class: "IN"
            type: "secondary"
            primaries:
              - "\"example-primary\""
            file: "{{ bind_multi_zone_file }}"
            allow_update_forwarding:
              - "key ddns"
    host_vars:
      bind-primary:
        bind_multi_ip: "172.29.253.10"
        bind_multi_primary_ip: "172.29.253.10"
        bind_multi_secondary_ip: "172.29.253.11"
        bind_multi_update_ip: "192.0.2.10"
        bind_multi_zone_file: "/var/named/dynamic/db.example.com"
      bind-secondary:
        bind_multi_ip: "172.29.253.11"
        bind_multi_primary_ip: "172.29.253.10"
        bind_multi_secondary_ip: "172.29.253.11"
        bind_multi_zone_file: "/var/named/dynamic/db.example.com"
verifier:
  name: "ansible"
scenario:
  name: "multi"
platforms:
  - name: "bind-primary"
    image: "docker.io/${uns:-jomrr}/molecule-${img:-fedora}:${tag:-latest}"
    pre_build_image: true
    override_command: false
    systemd: true
    network: "bind-multi"
    subnet: "172.29.253.0/24"
    ip: "172.29.253.10"
    groups:
      - "bind_multi"
      - "bind_multi_primary"
  - name: "bind-secondary"
    image: "docker.io/${uns:-jomrr}/molecule-${img:-fedora}:${tag:-latest}"
    pre_build_image: true
    override_command: false
    systemd: true
    network: "bind-multi"
    ip: "172.29.253.11"
    groups:
      - "bind_multi"
      - "bind_multi_secondary"
