---
# role: bind
# file: tasks/assert.yml

- name: "BIND | Validate unique effective zone file paths"
  ansible.builtin.assert:
    that:
      - >-
        (
          __bind_effective_zones
          | selectattr('file_path', 'defined')
          | map(attribute='file_path')
          | list
          | length
        ) == (
          __bind_effective_zones
          | selectattr('file_path', 'defined')
          | map(attribute='file_path')
          | unique(case_sensitive=true)
          | list
          | length
        )
    fail_msg: "Effective zone file paths must be unique."
    quiet: true
