---
# role: bind
# file: tasks/main.yml

- name: "BIND | Set os_family variables"
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"

- name: "BIND | Set distribution variables"
  ansible.builtin.include_vars: "{{ item }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      paths:
        - "vars"
      skip: true
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: "BIND | Install packages"
  ansible.builtin.package:
    name: "{{ __bind_packages }}"
    state: present

- name: "BIND | Create directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ __bind_directories }}"

- name: "BIND | Configure TSIG keys"
  ansible.builtin.include_tasks: "tsig.yml"
  when: bind_tsig_keys | length > 0

- name: "BIND | Configure zone files"
  ansible.builtin.include_tasks: "zone.yml"
  when: bind_zone_definitions | length > 0

- name: "BIND | Generate configuration files"
  ansible.builtin.template:
    src: "{{ __bind_config_file.src }}"
    dest: "{{ __bind_config_file.dest }}"
    owner: root
    group: "{{ __bind_group }}"
    mode: "0640"
    validate: "{{ __bind_config_file.validate | default(omit) }}"
  loop: "{{ __bind_config_files }}"
  loop_control:
    loop_var: __bind_config_file
    label: "{{ __bind_config_file.dest }}"
  notify:
    - "BIND | Validate configuration"
    - "BIND | Restart service"

- name: "BIND | Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "BIND | Enable and start service"
  ansible.builtin.systemd:
    name: "{{ __bind_service_name }}"
    state: started
    enabled: true
