---
# role: bind
# file: tasks/zone.yml

- name: "BIND | Generate zone files"
  ansible.builtin.template:
    src: "zone.j2"
    dest: "{{ __bind_zone_file.file }}"
    owner: "{{ __bind_user }}"
    group: "{{ __bind_group }}"
    mode: "0640"
    validate: "{{ __bind_checkzone_command }} {{ __bind_zone_file.name }} %s"
  loop: "{{ bind_zone_files }}"
  loop_control:
    loop_var: __bind_zone_file
    label: "{{ __bind_zone_file.name }}"
  notify:
    - "BIND | Validate configuration"
    - "BIND | Restart service"
