---
# role: bind
# file: tasks/zone.yml

- name: "BIND | Inspect existing zone file"
  ansible.builtin.stat:
    path: "{{ __bind_zone.file_path }}"
    get_checksum: false
    get_mime: false
  register: __bind_zone_file

- name: "BIND | Read existing SOA serial"
  ansible.builtin.command:
    argv:
      - "{{ __bind_checkzone_command }}"
      - -D
      - -s
      - relative
      - -q
      - -o
      - "-"
      - "{{ __bind_zone.name }}"
      - "{{ __bind_zone.file_path }}"
  register: __bind_zone_existing
  changed_when: false
  check_mode: false
  when: __bind_zone_file.stat.exists

- name: "BIND | Configure static zone"
  vars:
    __bind_zone_serial: >-
      {{
        (__bind_zone_existing.stdout | regex_search(__bind_zone_serial_regexp, '\2') | first)
        if __bind_zone_file.stat.exists
        else ansible_facts.date_time.epoch
      }}
  block:
    - name: "BIND | Generate zone file"
      ansible.builtin.template:
        src: "zone.j2"
        dest: "{{ __bind_zone.file_path }}"
        owner: "{{ __bind_zone_targets[__bind_zone.target_class].owner }}"
        group: "{{ __bind_zone_targets[__bind_zone.target_class].group }}"
        mode: "{{ __bind_zone_targets[__bind_zone.target_class].mode }}"
        backup: true
        validate: "{{ __bind_checkzone_command }} {{ __bind_zone.name }} %s"
      register: __bind_zone_template
      notify: restart

    - name: "BIND | Update zone serial"
      ansible.builtin.replace:
        path: "{{ __bind_zone.file_path }}"
        regexp: "{{ __bind_zone_serial_regexp }}"
        replace: '\g<1>{{ [(__bind_zone_serial | int + 1), (ansible_facts.date_time.epoch | int)] | max }}\g<3>'
        backup: true
        validate: "{{ __bind_checkzone_command }} {{ __bind_zone.name }} %s"
      when:
        - __bind_zone_file.stat.exists
        - __bind_zone_template.changed
      notify: restart
