---
# role: bind
# file: handlers/main.yml

- name: "BIND | Validate configuration"
  ansible.builtin.command: "{{ __bind_checkconf_command | replace('%s', __bind_conf_file) }}"
  changed_when: false

- name: "BIND | Restart service"
  ansible.builtin.systemd:
    name: "{{ __bind_service_name }}"
    state: restarted
