---
# role: bind
# file: molecule/resources/playbooks/verify.yml

- name: "Molecule | verify | bind"
  hosts: all
  gather_facts: false
  tasks:
    - name: "BIND | Query default localhost resolver"
      ansible.builtin.command:
        argv:
          - dig
          - "@127.0.0.1"
          - version.bind
          - TXT
          - CH
          - +tries=1
          - +time=2
      register: __bind_verify_default_query
      changed_when: false
      until:
        - __bind_verify_default_query.rc == 0
      retries: 10
      delay: 2
