---
# role: bind
# file: molecule/resources/playbooks/verify.yml

- name: "BIND | Verify default localhost resolver"
  hosts: all
  gather_facts: false
  tasks:
    - name: "BIND | Wait for default localhost resolver"
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 53
        timeout: 20
