---
# role: bind
# file: molecule/forwarder/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "verify.yml"
  inventory:
    group_vars:
      all:
        bind_molecule_dnsbl_valid_domain: "example.org"
        bind_molecule_dnsbl_blocked_domain: "example.com"
        bind_molecule_dnsbl_blocked_address: "0.0.0.0"
        bind_molecule_dnsbl_zone_name: "rpz.local"
        bind_listeners:
          - name: "listen-on"
            port: 53
            entries:
              - "127.0.0.1"
          - name: "listen-on-v6"
            port: 53
            entries:
              - "none"
        bind_options:
          - name: "recursion"
            value: "yes"
          - name: "forward"
            value: "only"
          - name: "forwarders"
            entries: "{{ ansible_facts.dns.nameservers }}"
          - name: "allow-query"
            entries:
              - "local"
          - name: "allow-query-cache"
            entries:
              - "local"
          - name: "allow-recursion"
            entries:
              - "local"
          - name: "allow-transfer"
            entries:
              - "none"
          - name: "dnssec-validation"
            value: "no"
          - name: "response-policy"
            entries:
              - "zone \"{{ bind_molecule_dnsbl_zone_name }}\""
          - name: "minimal-responses"
            value: "yes"
          - name: "version"
            value: "none"
        bind_zones:
          - name: "{{ bind_molecule_dnsbl_zone_name }}"
            class: "IN"
            type: "primary"
            file: "{{ bind_molecule_dnsbl_zone_file }}"
        bind_zone_files:
          - name: "{{ bind_molecule_dnsbl_zone_name }}"
            file: "{{ bind_molecule_dnsbl_zone_file }}"
            primary: "localhost."
            email: "hostmaster.localhost."
            records:
              - name: "@"
                type: "NS"
                data: "localhost."
              - name: "{{ bind_molecule_dnsbl_blocked_domain }}"
                type: "A"
                data: "{{ bind_molecule_dnsbl_blocked_address }}"
    host_vars:
      almalinux-latest-bind:
        bind_molecule_dnsbl_zone_file: "/var/named/dynamic/db.rpz.local"
      debian-latest-bind:
        bind_molecule_dnsbl_zone_file: "/var/cache/bind/db.rpz.local"
      fedora-latest-bind:
        bind_molecule_dnsbl_zone_file: "/var/named/dynamic/db.rpz.local"
      opensuse-leap-latest-bind:
        bind_molecule_dnsbl_zone_file: "/var/lib/named/dyn/db.rpz.local"
      opensuse-tumbleweed-latest-bind:
        bind_molecule_dnsbl_zone_file: "/var/lib/named/dyn/db.rpz.local"
      ubuntu-latest-bind:
        bind_molecule_dnsbl_zone_file: "/var/cache/bind/db.rpz.local"
verifier:
  name: "ansible"
scenario:
  name: "forwarder"
platforms:
  - name: "almalinux-latest-bind"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: "debian-latest-bind"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: "fedora-latest-bind"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: "opensuse-leap-latest-bind"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: "opensuse-tumbleweed-latest-bind"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: "ubuntu-latest-bind"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: true
